Repository kabir0x23/MovieLand, pull requests merged in 2022-10, with the labels that each got.

#29 New feature - Added release date below movie name in card
  src/App.css
  src/MovieCard.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#32 Remove console warnings
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#34 Added Dark Mode
  src/App.css
  src/App.js
  src/MovieCard.jsx
Labels: hacktoberfest

#43 updated cursor in DarkMode Btn
  src/App.css
Labels: hacktoberfest, hacktoberfest-accepted

#45 [FEATURE]Added Scroll to top Button [Fixes #42]
  package-lock.json
  public/index.html
  src/App.css
  src/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#47 Added custom scrollbar in webpage
  public/index.html
Labels: hacktoberfest, hacktoberfest-accepted
